/* HTTP */
const HTTP_OK = 200;
const HTTP_CREATED = 201;
const HTTP_BAD_REQUEST = 400;
const HTTP_UNAUTHORIZED = 401;
const HTTP_REQUEST_FAILED = 402;
const HTTP_FORBIDDEN = 403;
const HTTP_NOT_FOUND = 404;

module.exports = {
  HTTP_OK,
  HTTP_CREATED,
  HTTP_BAD_REQUEST,
  HTTP_UNAUTHORIZED,
  HTTP_REQUEST_FAILED,
  HTTP_FORBIDDEN,
  HTTP_NOT_FOUND,
};
